# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'developer_id: 3, name: ' ', Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

project_1 = Project.create(developer_id: 3, name: 'Mauris et', started: '2020-10-09', deadline: '2021-01-27', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ullamcorper ligula vel facilisis gravida. Vivamus ultrices leo quis nisi consequat, sit amet dapibus odio mollis. Praesent rhoncus nec lacus eu euismod. Etiam lacus nisi, fringilla a vulputate sed, vulputate at purus. Sed dapibus congue iaculis. Cras semper imperdiet pretium. Sed non fermentum metus, vel posuere sem. Donec accumsan, mauris at lobortis lobortis, nibh velit molestie tellus, a tincidunt ipsum neque quis turpis. Phasellus quis porta erat.', completed: true )
project_2 = Project.create(developer_id: 3, name: 'Cras interdum', started: '2020-11-05', deadline: '2021-03-10', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ullamcorper ligula vel facilisis gravida. Vivamus ultrices leo quis nisi consequat, sit amet dapibus odio mollis. Praesent rhoncus nec lacus eu euismod. Etiam lacus nisi, fringilla a vulputate sed, vulputate at purus. Sed dapibus congue iaculis. Cras semper imperdiet pretium. Sed non fermentum metus, vel posuere sem. Donec accumsan, mauris at lobortis lobortis, nibh velit molestie tellus, a tincidunt ipsum neque quis turpis. Phasellus quis porta erat.', completed: true)
project_3 = Project.create(developer_id: 3, name: 'Integer ultrices', started: '2020-11-16', deadline: '2021-03-26', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ullamcorper ligula vel facilisis gravida. Vivamus ultrices leo quis nisi consequat, sit amet dapibus odio mollis. Praesent rhoncus nec lacus eu euismod. Etiam lacus nisi, fringilla a vulputate sed, vulputate at purus. Sed dapibus congue iaculis. Cras semper imperdiet pretium. Sed non fermentum metus, vel posuere sem. Donec accumsan, mauris at lobortis lobortis, nibh velit molestie tellus, a tincidunt ipsum neque quis turpis. Phasellus quis porta erat.', completed: false)
project_4 = Project.create(developer_id: 3, name: 'Aenean vulputate', started: '2020-11-19', deadline: '2021-05-27', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ullamcorper ligula vel facilisis gravida. Vivamus ultrices leo quis nisi consequat, sit amet dapibus odio mollis. Praesent rhoncus nec lacus eu euismod. Etiam lacus nisi, fringilla a vulputate sed, vulputate at purus. Sed dapibus congue iaculis. Cras semper imperdiet pretium. Sed non fermentum metus, vel posuere sem. Donec accumsan, mauris at lobortis lobortis, nibh velit molestie tellus, a tincidunt ipsum neque quis turpis. Phasellus quis porta erat.', completed: false)
project_5 = Project.create(developer_id: 3, name: 'Nunc tempus', started:'', deadline: '2021-08-13', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ullamcorper ligula vel facilisis gravida. Vivamus ultrices leo quis nisi consequat, sit amet dapibus odio mollis. Praesent rhoncus nec lacus eu euismod. Etiam lacus nisi, fringilla a vulputate sed, vulputate at purus. Sed dapibus congue iaculis. Cras semper imperdiet pretium. Sed non fermentum metus, vel posuere sem. Donec accumsan, mauris at lobortis lobortis, nibh velit molestie tellus, a tincidunt ipsum neque quis turpis. Phasellus quis porta erat.', completed: false)
project_6 = Project.create(developer_id: 3, name: 'Aenean nec', started:'', deadline: '2021-10-19', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ullamcorper ligula vel facilisis gravida. Vivamus ultrices leo quis nisi consequat, sit amet dapibus odio mollis. Praesent rhoncus nec lacus eu euismod. Etiam lacus nisi, fringilla a vulputate sed, vulputate at purus. Sed dapibus congue iaculis. Cras semper imperdiet pretium. Sed non fermentum metus, vel posuere sem. Donec accumsan, mauris at lobortis lobortis, nibh velit molestie tellus, a tincidunt ipsum neque quis turpis. Phasellus quis porta erat.', completed: false)
project_7 = Project.create(developer_id: 3, name: 'Proin faucibus', started:'', deadline: '2021-10-27', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ullamcorper ligula vel facilisis gravida. Vivamus ultrices leo quis nisi consequat, sit amet dapibus odio mollis. Praesent rhoncus nec lacus eu euismod. Etiam lacus nisi, fringilla a vulputate sed, vulputate at purus. Sed dapibus congue iaculis. Cras semper imperdiet pretium. Sed non fermentum metus, vel posuere sem. Donec accumsan, mauris at lobortis lobortis, nibh velit molestie tellus, a tincidunt ipsum neque quis turpis. Phasellus quis porta erat.', completed: false)
project_8 = Project.create(developer_id: 3, name: 'Mauris consectetur', started:'', deadline: '2021-12-10', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ullamcorper ligula vel facilisis gravida. Vivamus ultrices leo quis nisi consequat, sit amet dapibus odio mollis. Praesent rhoncus nec lacus eu euismod. Etiam lacus nisi, fringilla a vulputate sed, vulputate at purus. Sed dapibus congue iaculis. Cras semper imperdiet pretium. Sed non fermentum metus, vel posuere sem. Donec accumsan, mauris at lobortis lobortis, nibh velit molestie tellus, a tincidunt ipsum neque quis turpis. Phasellus quis porta erat.', completed: false)

# Developer.create(name: 'Mary Perkins')