# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Assignment.create(started: '2020-10-09', deadline: '2021-01-27', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ullamcorper ligula vel facilisis gravida. Vivamus ultrices leo quis nisi consequat, sit amet dapibus odio mollis. Praesent rhoncus nec lacus eu euismod. Etiam lacus nisi, fringilla a vulputate sed, vulputate at purus. Sed dapibus congue iaculis. Cras semper imperdiet pretium. Sed non fermentum metus, vel posuere sem. Donec accumsan, mauris at lobortis lobortis, nibh velit molestie tellus, a tincidunt ipsum neque quis turpis. Phasellus quis porta erat.', completed: true )
Assignment.create(started: '2020-11-05', deadline: '2021-03-10', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ullamcorper ligula vel facilisis gravida. Vivamus ultrices leo quis nisi consequat, sit amet dapibus odio mollis. Praesent rhoncus nec lacus eu euismod. Etiam lacus nisi, fringilla a vulputate sed, vulputate at purus. Sed dapibus congue iaculis. Cras semper imperdiet pretium. Sed non fermentum metus, vel posuere sem. Donec accumsan, mauris at lobortis lobortis, nibh velit molestie tellus, a tincidunt ipsum neque quis turpis. Phasellus quis porta erat.', completed: true)
Assignment.create(started: '2020-11-16', deadline: '2021-03-26', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ullamcorper ligula vel facilisis gravida. Vivamus ultrices leo quis nisi consequat, sit amet dapibus odio mollis. Praesent rhoncus nec lacus eu euismod. Etiam lacus nisi, fringilla a vulputate sed, vulputate at purus. Sed dapibus congue iaculis. Cras semper imperdiet pretium. Sed non fermentum metus, vel posuere sem. Donec accumsan, mauris at lobortis lobortis, nibh velit molestie tellus, a tincidunt ipsum neque quis turpis. Phasellus quis porta erat.', completed: false)
Assignment.create(started: '2020-11-19', deadline: '2021-05-27', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ullamcorper ligula vel facilisis gravida. Vivamus ultrices leo quis nisi consequat, sit amet dapibus odio mollis. Praesent rhoncus nec lacus eu euismod. Etiam lacus nisi, fringilla a vulputate sed, vulputate at purus. Sed dapibus congue iaculis. Cras semper imperdiet pretium. Sed non fermentum metus, vel posuere sem. Donec accumsan, mauris at lobortis lobortis, nibh velit molestie tellus, a tincidunt ipsum neque quis turpis. Phasellus quis porta erat.', completed: false)
Assignment.create(started: nil, deadline: '2021-08-13', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ullamcorper ligula vel facilisis gravida. Vivamus ultrices leo quis nisi consequat, sit amet dapibus odio mollis. Praesent rhoncus nec lacus eu euismod. Etiam lacus nisi, fringilla a vulputate sed, vulputate at purus. Sed dapibus congue iaculis. Cras semper imperdiet pretium. Sed non fermentum metus, vel posuere sem. Donec accumsan, mauris at lobortis lobortis, nibh velit molestie tellus, a tincidunt ipsum neque quis turpis. Phasellus quis porta erat.', completed: false)
Assignment.create(started: nil, deadline: '2021-10-19', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ullamcorper ligula vel facilisis gravida. Vivamus ultrices leo quis nisi consequat, sit amet dapibus odio mollis. Praesent rhoncus nec lacus eu euismod. Etiam lacus nisi, fringilla a vulputate sed, vulputate at purus. Sed dapibus congue iaculis. Cras semper imperdiet pretium. Sed non fermentum metus, vel posuere sem. Donec accumsan, mauris at lobortis lobortis, nibh velit molestie tellus, a tincidunt ipsum neque quis turpis. Phasellus quis porta erat.', completed: false)
Assignment.create(started: nil, deadline: '2021-10-27', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ullamcorper ligula vel facilisis gravida. Vivamus ultrices leo quis nisi consequat, sit amet dapibus odio mollis. Praesent rhoncus nec lacus eu euismod. Etiam lacus nisi, fringilla a vulputate sed, vulputate at purus. Sed dapibus congue iaculis. Cras semper imperdiet pretium. Sed non fermentum metus, vel posuere sem. Donec accumsan, mauris at lobortis lobortis, nibh velit molestie tellus, a tincidunt ipsum neque quis turpis. Phasellus quis porta erat.', completed: false)
Assignment.create(started: nil, deadline: '2021-12-10', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ullamcorper ligula vel facilisis gravida. Vivamus ultrices leo quis nisi consequat, sit amet dapibus odio mollis. Praesent rhoncus nec lacus eu euismod. Etiam lacus nisi, fringilla a vulputate sed, vulputate at purus. Sed dapibus congue iaculis. Cras semper imperdiet pretium. Sed non fermentum metus, vel posuere sem. Donec accumsan, mauris at lobortis lobortis, nibh velit molestie tellus, a tincidunt ipsum neque quis turpis. Phasellus quis porta erat.', completed: false)

